### ISSUE TITLE
The report in travis seems wierd

### ISSUE THREAD

**Issue by zation** [DevExpress/testcafe#1469]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

![Travis](http://7xku8d.com1.z0.glb.clouddn.com/Screen%20Shot%202017-05-09%20at%205.21.10%20PM.png)

### What is the expected behavior?

The report should not be wrapped every word.

### How would you reproduce the current behavior (if this is a bug)?

Just run testcafe in travis. BTW, the report displays correctly in my local terminal.

### Specify your

* operating system: travis
* testcafe version: 0.15.0
* node.js version: 6

**Comment by AlexanderMoskovkin** [comment]
Hi,

It seems something went wrong when TestCafe [calculated the viewport width](https://github.com/DevExpress/testcafe/blob/master/src/utils/get-viewport-width.js#L6).
To resolve the problem set the teminal columns setting in the `.travis.yml` file:
```yml
before_install:
   - stty cols 78
```

**Comment by inikulin** [comment]
Hmm, I've seen this issue once, but was not able to reproduce it since then. @zation Is problem persists after retry?

**Comment by zation** [comment]
@inikulin yes, I tried @AlexanderMoskovkin solution, it works. Below is our previous travis config:

```yml
sudo: false
dist: trusty

language: node_js
node_js:
  - "6"
# cache yarn and node_modules directory
cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

notifications:
  email: false

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test
```
