### ISSUE TITLE
`resizeWindow, maximizeWindow, resizeWindowToFitDevice` functionality are not working when executing tests in Travis CI

### ISSUE THREAD

**Issue by avozicov** [DevExpress/testcafe#1730]
### Are you requesting a feature or reporting a bug?
- Reporting a bug

### What is the current behavior?
- `resizeWindow, maximizeWindow, resizeWindowToFitDevice` functionality are not working when executing tests in Travis CI
- issue is reproducing only when executing tests in Travis CI and everything works as expected on local machine
- The following errors are displayed in Travis log: 
`Was unable to resize the window due to an error.`(for Chrome, Firefox, Nightmare)
`Was unable to maximize the window due to an error.` (for Chrome, Firefox, Nightmare)
`The window maximization functionality is not supported by the nightmare browser provider.` (only for Nightmare)

### What is the expected behavior?
- `resizeWindow, maximizeWindow, resizeWindowToFitDevice` functionality should work for CI the same as on local machine 

### How would you reproduce the current behavior (if this is a bug)?
- Write a script with `resizeWindow, maximizeWindow, resizeWindowToFitDevice` functions 
- Specify the selector which become visible only after resizing the window 
- Assert the required selector to be visible or simulate click action 

Tested page URL:
- https://www-test.adtechmedia.io/

### Specify your
* environment: Travis CI
* operating system: Linux
* testcafe version: v0.17.0
* node.js version:  v8.4.0

**Comment by AndreyBelym** [comment]
Hello @avozicov! Have you followed our recipe for Travis CI: https://devexpress.github.io/testcafe/documentation/recipes/running-tests-in-firefox-and-chrome-using-travis-ci.html?

**Comment by avozicov** [comment]
Hello @AndreyBelym !
Thank you for the reply ;)

Yes, I have followed the instructions from your documentation and we are not facing any issues with running tests in Travis CI. The scripts which are not using `resizeWindow, maximizeWindow, resizeWindowToFitDevice` are passed and everything is working as expected so I am not sure there something wrong with Travis configuration.
Here is an example of .travis.yml file from our repository 

```
language: node_js
git:
  depth: 1
cache:
  bundler: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - stage
    - test
    - build
    - dev
env:
  global:
    - DEEP_NO_INTERACTION=1
    # AWS_ACCOUNT_ID=[secure]
    - secure:

stage: "Run Unit Tests :clipboard:"
node_js:
  - 6
  - 8
before_install:
  - source bin/deploy/init.sh
script:
  - recink run unit -c recink-codeclimate -c recink-snyk

jobs:
  include:
    - stage: "Deploy To :cloud:"
      node_js: 6
      script:
        - if [ ${ALLOW_DEPLOY} == 1 ]; then node bin/deploy; else echo "Skipping deploy"; fi
      after_failure:
        - deepify undeploy src --loglevel=debug

    - stage: "Run e2e Tests :clipboard:"
      node_js: 8
      script:
        - if [ ${ALLOW_DEPLOY} == 1 ]; then recink run e2e; else echo "Skipping e2e tests"; fi
      addons:
        firefox: 'latest'
        chrome: 'beta'
        apt:
          packages:
            - xvfb
      install:
        - 'export DISPLAY='':99.0'''
        - 'Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &'

    - stage: "Page speed :rocket:"
      node_js: 6
      script:
        - if [ ${ALLOW_DEPLOY} == 1 ]; then recink run unit -s emit -c recink-pagespeed; else echo "Skipping pagespeed"; fi
```

**Comment by AndreyBelym** [comment]
Currently TestCafe requires ICCCM/EWMH-compliant window manager for this functionality, e.g. `fluxbox`. Check this fragment of `.travis.yml` from the Travis CI recipe:
```
addons:
  apt:
    packages:
     - fluxbox

before_script:
  - fluxbox >/dev/null 2>&1 &
```
