### ISSUE TITLE
Screenshots with default docker container are black

### ISSUE THREAD

**Issue by Thomblin** [DevExpress/testcafe#1882]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

I use the default testcafe/testcafe container with entrypoint `["/opt/testcafe/docker/testcafe-docker.sh", "-c", "2", "-S", "-s", "/testcafe/screenshots", "firefox", "/testcafe/tests"]`

However all screenshots taken by chromium or firefox are black

### What is the expected behavior?

I would expect to see a browser snapshot of the current screen

### How would you reproduce the current behavior (if this is a bug)?

```
testcafe:
    image: testcafe/testcafe
    container_name: serp_testcafe
    environment:
      - NODE_PATH=/opt/testcafe/node_modules:/opt
    volumes:
      - ./src/testcafe:/testcafe
      - ./node_modules/testcafe-react-selectors:/opt/testcafe/node_modules/testcafe-react-selectors
    depends_on:
      - serp
    entrypoint: ["/opt/testcafe/docker/testcafe-docker.sh", "-c", "2", "-S", "-s", "/testcafe/screenshots", "firefox", "/testcafe/tests"]
```

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: docker container testcafe/testcafe 
* testcafe version: latest
* node.js version: as provided in docker container
