### ISSUE TITLE
Run testcafe in GitLab-CI doesn't work

### ISSUE THREAD

**Issue by Gwerlas** [DevExpress/testcafe#2747]
Tested with testcafe 0.21.1

In my CI pipeline, I have this job :

```yaml
e2e:
  image: testcafe/testcafe
  script:
    - "chromium --no-sandbox" -a "npm start" tests/e2e/
```

Because a CI job can have a multiple lines script, Gitlab-CI run the given image with the `script` instruction joined by ";". So In my case, testcafe is launched like this :

```
docker run testcafe/testcafe sh -c '"chromium --no-sandbox" -a "npm start" tests/e2e/'
```

Resulting in this :

```
ERROR Unable to find the browser. "sh" is not a browser alias or path to an executable file.

Type "testcafe -h" for help
```

So, I tried to force the entrypoint to a shell like this :

```yaml
e2e:
  image: 
    name: testcafe/testcafe
    entrypoint: ["/bin/sh"]
  script:
    - /opt/testcafe/docker/testcafe-docker.sh "chromium --no-sandbox" -a "npm start" tests/e2e/
```

But in this case, I have this behaviour :

```
/bin/sh: can't open 'sh': No such file or directory
```

I'm not sure why, but I saw that the two valids shells `/bin/ash` and `/bin/sh` are symlinks to busybox.

I don't know how to fix this...

**Comment by AndreyBelym** [comment]
Hi @Gwerlas, thanks for explaining how GitLab CI actually works! You were right about overriding image's entrypoint, but you had missed the `-c` argument of `/bin/sh` that tells the shell that next arguments aren't a script files, but a command. So correct `gitlooks like:
```
e2e:
  image: 
    name: testcafe/testcafe
    entrypoint: ["/bin/sh". "-c"]
  script:
    - /opt/testcafe/docker/testcafe-docker.sh "chromium --no-sandbox" -a "npm start" tests/e2e/
```  

Check my example: [.gitlab-ci.yml](https://gitlab.com/AndreyBelym/testcafe/blob/fb1d732e6d2469910fa276036498d6e142f71d82/.gitlab-ci.yml), [GitLab Pipelline](https://gitlab.com/AndreyBelym/testcafe/-/jobs/90600212)
