### ISSUE TITLE
Docs: some recipes would be quite useful (discussion)

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#287]
- [x] Travis-CI + SauceLabs (#775)
- [x] AppVeyor
- [x] Travis-CI with phantomjs or Chrome (you don't need SauceLabs to run test in Chrome)
- [x] Using with Gulp
- [x] Using with Grunt
- [x] Testing on Remote Computers and Mobile Devices
- [ ] Debugging
  - [x] Visual Studio Code
  - [ ] WebStorm
  - [x] Chrome Dev Tools
- [x] "page model" pattern (#724)
- [x] circleci (react, vue, angular)
- [x] Jenkins and TeamCity

**Comment by AlexanderMoskovkin** [comment]
@AndreyBelym is working on `Travis-CI with phantomjs or Chrome (you don't need SauceLabs to run test in Chrome)`

**Comment by AlexanderMoskovkin** [comment]
I'm working on `"page model" pattern`

**Comment by miherlosev** [comment]
Also add recipes for 
 - [circleci](https://circleci.com/) (react, vue, angular)
 - [houndci](https://houndci.com/) (bootstrap)

**Comment by VasilyStrelyaev** [comment]
Working on the `using with gulp` recipe

**Comment by AlexanderMoskovkin** [comment]
I've added one more idea: `Using with Grunt` (https://www.npmjs.com/package/grunt-testcafe)

**Comment by georgiy-abbasov** [comment]
I think, recipe with TDD example may be usefull

**Comment by mjhea0** [comment]
In terms of circle, my tests are just working with the following in my circle.yml file:

```yaml
machine:
  node:
    version: 7.6.0
```

I tested breaking changes as well. Works.

@miherlosev

**Comment by mjhea0** [comment]
https://circleci.com/gh/mjhea0/testcafe-example/3

https://github.com/mjhea0/testcafe-example/blob/master/circle.yml

**Comment by miherlosev** [comment]
hi mjhea0
We will create a recipe for circle ci in one of the upcoming sprints

**Comment by mjhea0** [comment]
@miherlosev thanks!

how about coupling testcafe with a bdd tool?

**Comment by miherlosev** [comment]
What bdd tool do you want to couple with testcafe?

**Comment by mjhea0** [comment]
I saw the cucumberjs example -> https://github.com/helen-dikareva/testcafe-cucumber-demo/blob/master/features/step_definitions/github.js Looks good!

I would love to be able to use mocha, but as of now mocha needs the tests to be ran with `mocha` to expose the API -> https://github.com/mochajs/mocha/issues/1849. This looks like a similar issue for testcafe. Any way to programmatically require or import in the necessary methods so I can just use mocha as the runner?

https://github.com/mjhea0/testcafe-example/blob/bdd/tests/bdd.js

**Comment by inikulin** [comment]
@mjhea0 I'm not sure it will be possible to cooperate mocha with TestCafe, since later uses a lot of magic in `test` and `fixture` calls, so you will need to use them, instead of mocha's methods. However, we have a feature request open to support BDD style tests (nested fixtures + reporting): https://github.com/DevExpress/testcafe/issues/792 Add your 👍 to the issue if you are interested and we consider adding to the planned feature list.

**Comment by mjhea0** [comment]
Do you have any recipes for circle 2.0? @inikulin

**Comment by inikulin** [comment]
@mjhea0 We don't have any recipes for circle at the moment.

**Comment by mjhea0** [comment]
I have circle 1 complete. I am working through Circle 2 at the moment. Happy to add them as recipes when I get Circle 2 working. 

Running into some problems with xvfb and the display. Can I show you what I have thus far?

**Comment by inikulin** [comment]
@mjhea0 Sure, feel free to share anything you have.

**Comment by rstudner** [comment]
@mjhea0 - i'm about to start trying to use testcafe w/ circle 2.0.  Any more luck on that?

**Comment by mjhea0** [comment]
@rstudner Yes, I got it working. I'll share the script with you later today.

**Comment by mjhea0** [comment]
@rstudner I have not looked at this in like 4 months, but here it is:

```
version: 2

defaults: &defaults
  docker:
    - image: circleci/node:7-browsers
  working_directory: ~/tests

jobs:
  build:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install testcafe
      - run:
          name: Run tests
          command: |
            mkdir /tmp/artifacts;
            testcafe chrome 'tests/test.js' -S -s tmp/artifacts
```
