### ISSUE TITLE
Running testcafe in container network has DNS resolution failure

### ISSUE THREAD

**Issue by Zebirdman** [DevExpress/testcafe#3485]
### What is the Current behaviour?
 I am using docker compose to launch a web application running from quasar, a back end using express and your latest (as of 10 days ago) testcafe container on windows 10 using docker engine (they are all linux containers).

I am trying to run the test cafe container internally on the container network by injecting the name of the front end web container into my tests file as I could not get localhost to resolve correctly. Both front end and back end containers can ping via their respective container names, I have also added a extra_hosts entry on the testcafe compose configuration to add the front ends IP to the /etc/hosts file. The entry is added with correct IP (i am using static IP's on a custom network for now) but will not resolve. On top of this I tried injecting the IP address directly and this still throws the error. 

I have tried running chrome with the --dns-prefetch-disabe flag, I am doing all of this using https
 
### What is the Expected behavior?
The chrome container should be able to resolve the IP address of the docker compose service. Is this a chrome issue?
 
Here is an extract from the docker-compose file i am using (API server removed for simplicity but it can reach the web server on 'pivot-web')

```yml
  pivot-web:
    build: 
      context: ../../
      dockerfile: ******
    container_name: pivot-web
    depends_on: 
      - pivot-api
    ports:
      - "8082:8082"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    command: ["node", "node_modules/quasar-cli/bin/quasar-dev"]

  test-cafe:
    image: testcafe/testcafe
    container_name: "testcafe"
    depends_on: 
      - pivot-web
    environment:
      - USE_INTERNAL_DNS=true
    ports:
      - "1337:1337"
      - "1338:1338"
    volumes:
      - ../:/tests
    cap_add:
      - ALL
    networks:
      app_net:
        ipv4_address: 172.16.238.12
    extra_hosts:
      - "pivot-web:172.16.238.10"
    command: ["chromium --no-sandbox --allow-insecure-localhost --dns-prefetch-disable", "/tests/tests/*.test.js"]

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24
```
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 const address = process.env.USE_INTERNAL_DNS ? "pivot-web" : "localhost";

const userRole = Role(`https://${address}:8082/login`, async t => {
  await loginPage.login(credentials);
  await t.wait(5000);
  await localStorageSet('settings', demoState);
  console.log(`[INFO] loaded page state: `, await localStorageGet('settings'));
  await t.wait(5000);
}, { preserveUrl: true });

// eslint-disable-next-line no-undef
fixture`[INFO] Log in and test user matching`
  .page(`https://${address}:8082/login`);

// eslint-disable-next-line no-undef
test("[INFO] Running Test: Check matching page state", async t => {
  if (process.env.USE_INTERNAL_DNS) {
    await t.wait(40000);
  }
  await t.useRole(userRole);
```
Test results simplified output
```
 [INFO] Log in and test user matching
 ✖ [INFO] Running Test: Check matching page state

   1) Failed to find a DNS-record for the resource at
      "https://pivot-web:8082/login".

      Browser: Chrome 71.0.3578 / Linux 0.0.0
```
The test runs fine when run locally against the the front end container in my local chrome, my local testcafe version is 1.0.1
