### ISSUE TITLE
click previous element in testcafe

### ISSUE THREAD

**Issue by daenerysr** [DevExpress/testcafe#3931]
Hi,

I have a grid with edit link beside each products name and i have total 4 products.
All the products edit buttons are dynamic.
e.g.
edit(link) product name
edit(link) product name

I am able to locate to product text but need to find previous element (edit link).

In selenium i was using the below xpath but not able to apply same in testcafe:
"//b[contains(text(), 'Professional')]/preceding::td[@name='LACTION'][1]")

**Comment by Farfurix** [comment]
Hello,

Please refer to the "[Search for Elements in the DOM Hierarchy](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/functional-style-selectors.html#prevsibling)" documentation section.

I prepared the following "prevSibling" sample:
![Capture](https://user-images.githubusercontent.com/30019338/60186247-10421b80-9834-11e9-8979-28915cac84f7.PNG)
**index.html**:
```html
<html>
<head>
    <link rel="stylesheet" href="style.css">
</head>
<body>
<div class="wrapper">
    <div>One</div>
    <div>Two</div>
    <div>Three</div>
    <div>Four</div>
    <div>Five</div>
    <div>Six</div>
</div>
</body>
</html>

```

**style.css**:
```css
.wrapper {
    display: grid;
    grid-template-columns: 200px 200px;
}
* {box-sizing: border-box;}
.wrapper {
    border: 2px solid #f76707;
    border-radius: 5px;
    background-color: #fff4e6;
}
.wrapper > div {
    border: 2px solid #ffa94d;
    border-radius: 5px;
    background-color: #ffd8a8;
    padding: 1em;
    color: #d9480f;
}
.nested {
    border: 2px solid #ffec99;
    border-radius: 5px;
    background-color: #fff9db;
    padding: 1em;
}

```

**test.js**:
```js
import { Selector } from 'testcafe';

fixture `Fixture`
    .page `http://localhost:8080/`

test('test', async t => {
    const selectorFourPrevSibling = Selector('div > div').withText('Four').prevSibling(-1).addCustomDOMProperties({
        innerHTML: el => el.innerHTML
    });

    const selectorSixPrevSibling = Selector('div > div').withText('Six').prevSibling(-1).addCustomDOMProperties({
        innerHTML: el => el.innerHTML
    });

    console.log('selectorFourPrevSibling.innerHTML =', await selectorFourPrevSibling.innerHTML);
    console.log('selectorSixPrevSibling.innerHTML =', await selectorSixPrevSibling.innerHTML);

    await t
        .expect(selectorFourPrevSibling.innerHTML).eql('Three')
        .expect(selectorSixPrevSibling.innerHTML).eql('Five');

});

```
