### ISSUE TITLE
I have written testcases which is passing in my machine. But, while trying in Travis failing.

### ISSUE THREAD

**Issue by Haribalajiravi** [DevExpress/testcafe#4741]
### What is your Test Scenario?
```
import { Selector } from 'testcafe';

fixture `Creamie Basis Testcases`
    .page `http://localhost:8080/tests/test_example/src/index.html`;

test('Binder: input value reflection in dom', async t => {
    await t
        .typeText('#binder-textbox', 'creamie')
        .expect(Selector('#binder-reflecter').innerText).eql('creamie');
});

test('Events: click event', async t => {
    await t
        .click('#event-click')
        .expect(Selector('#binder-reflecter').innerText).eql('Data Changed');
});
```
 
### What is the Current behavior?
Failing in travis. But passing in machine. 
Before it passed on travis:
https://github.com/Haribalajiravi/creamie/blob/3dbf1d6ac646209e82f007d5de02c7181587caf1/tests/testcases/test1.js
https://travis-ci.org/Haribalajiravi/creamie/builds/646975883

After its failling:
https://travis-ci.org/Haribalajiravi/creamie/jobs/647038108
https://github.com/Haribalajiravi/creamie/blob/master/tests/testcases/test1.js
 
### What is the Expected behavior?
It should pass the test
 
## .travis.yml (Before and after)
```
dist: trusty
os: linux
language: node_js
node_js:
- node
- '9'
addons:
  chrome: stable
  firefox: latest

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- fluxbox >/dev/null 2>&1 &
```
