### ISSUE TITLE
Docker image seems broken when run in Gitlab CI since 1.9.0-rc.2

### ISSUE THREAD

**Issue by gudoy** [DevExpress/testcafe#5421]
### What is your Test Scenario?
Running our E2E jobs in Gitlab CI with Docker image and the following conf
```yaml
e2e-chrome:
  stage: post-deploy QA
  tags:
    - cloud-dev
  image:
    # name: testcafe/testcafe:1.8.8 # OK
    #name: testcafe/testcafe:alpha  # OK
    #name: testcafe/testcafe:1.9.0-rc.1 # OK
    name: testcafe/testcafe:1.9.0-rc.2 # NOK
    #name: testcafe/testcafe:latest # NOK
    entrypoint: ["/bin/sh", "-c"]
  script:
    - /opt/testcafe/docker/testcafe-docker.sh "chromium --no-sandbox --no-proxy-server" -q --skip-uncaught-errors --skip-js-errors -r spec,json:e2e-report.json app/test/e2e/**/*.test.js
```
 
### What is the Current behavior?
The job fails with the following error
```
sh: write error: Invalid argument
ERROR: Job failed: command terminated with exit code 1
```
Downgrading the docker image to the version 'testcafe/testcafe:1.9.0-rc.1'  fixes the issue.
 
### What is the Expected behavior?
The job should run as it did before version 1.9.0-rc.2
