### ISSUE TITLE
Docker image 1.9.0-rc.2 errors out in Gitlab CI

### ISSUE THREAD

**Issue by devcarol** [DevExpress/testcafe#5645]
### Are you requesting a feature or reporting a bug?

This is similar to a previously reported issue (https://github.com/DevExpress/testcafe/issues/5421) but I don't see any resolution.

### What is your Test Scenario?

Gitlab config:
```
stages:
  - e2e-test
  
e2e:
  stage: e2e-test
  image:
    name: testcafe/testcafe
    entrypoint: ["/bin/sh", "-c"]
  only:
    - master
  script:
    - /opt/testcafe/docker/testcafe-docker.sh -v
  artifacts:
    when: on_failure
    paths:
      - tests/screenshots
```

### What is the Current behavior?

Pipeline error
```
Executing "step_script" stage of the job script
sh: write error: Invalid argument
```

### What is the Expected behavior?

Expecting the same behaviour when using image 1.9.0-rc.1
```
  image:
    name: testcafe/testcafe: 1.9.0-rc.1
```
Pipeline output
```
Executing "step_script" stage of the job script
$ /opt/testcafe/docker/testcafe-docker.sh -v
1.9.0-rc.1
```
