### ISSUE TITLE
Feature detection media query ignored?

### ISSUE THREAD

**Issue by fredboyle** [DevExpress/testcafe#6003]
### What is your Test Scenario?
Animations, particularly `hover` triggered ones that use CSS media queries such as `@media (hover: hover) and (pointer: fine) {`
 
### What is the Current behavior?
Media query is not triggered in TestCafé therefore animation/styles are not visible
 
### What is the Expected behavior?
Media query is triggered and animation is visible
 
### What is your web application and your TestCafe test code?
 
[JS Bin link](https://output.jsbin.com/diponofuyo)
<details>
<summary>Your website URL (or attach your complete example):</summary>

```css
@media (hover: none) {

    &:active {
      transform: scale(0.97);

      @media (prefers-reduced-motion: reduce) {
        transform: none;
      }
    }
  }

  @media (hover: hover) and (pointer: fine) {

    &:hover {
      transform: scale(1);

      @media (prefers-reduced-motion: reduce) {
        transform: none;
      }
    }

    &:active {
      transform: scale(0.97);
    }
  }
```
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 ('KX: Button – brand', async t => {
      await t
        .takeScreenshot({ path: 'buttons-base-examples--brand-kinetics__initial.png' })
        .hover('button')
        .takeScreenshot({ path: 'buttons-base-examples--brand-kinetics__hover.png' })
        .click('button')
        .takeScreenshot({ path: 'buttons-base-examples--brand-kinetics__click.png' })
        ;
    })
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "browsers": "chrome",
  "src": "testcafe/*.js",
  "screenshots": {
    "path": "testcafe/screenshots/"
  },
  "videoPath": "testcafe/videos"
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>
Expected:
![image](https://user-images.githubusercontent.com/32829/109693663-c8ae7f80-7b3e-11eb-8d97-9e4fd9ebcff1.png)

Actual:
![image](https://user-images.githubusercontent.com/32829/109693714-d95ef580-7b3e-11eb-805e-fbd65c109c17.png)

</details>

### Steps to Reproduce:

1. Load the following URL in TestCafé debug: https://output.jsbin.com/diponofuyo
2. Unlock page
3. Manually hover to see button color changes to pink instead of the expected orange
 
### Your Environment details:
 
* testcafe version:                   1.11.0
* node.js version:                    v12.16.1
* command-line arguments:  --debug-mode --speed 0.5
* browser name and version: Chrome 88
* platform and version:          macOS 10.15.7
* other:
