### ISSUE TITLE
Bitbucket pipeline: The double amount of errors is shown in bitbucket pipeline (xUnit)

### ISSUE THREAD

**Issue by ChristianThingKnudsen** [DevExpress/testcafe#6543]
### What is your Test Scenario?
Bitbucket pipelines
 
### What is the Current behavior?
The errors shown in bitbucket pipelines is doubled compared to the reporter (xUnit) 
 
### What is the Expected behavior?
The amount of errors shown in bitbucket pipeline should match the actual number of errors by the reporter
 
![Screenshot 2021-09-16 at 10 22 44](https://user-images.githubusercontent.com/27851699/133578513-d58ff315-35be-4c58-8a45-444391eb60d0.png)

### Minimal working example 

**test-fixture.js loacated at ./testcafe/fixtures/**

```
fixture("double error on bitbucket fixture").page("www.google.com");

test("Should not count error twice", async (t) => {
  await t.expect(true).eql(false);
});
```

 **bitbucket-pipelines.yml**

```
image: testcafe/testcafe
pipelines:
  pull-requests:
    "**":
      - step:
          script:
            - npm ci
            - /opt/testcafe/docker/testcafe-docker.sh 'firefox:headless,chromium --no-sandbox --disable-dev-shm-usage' testcafe/fixtures/test-fixture.js -r xunit:reports/test-results/bitbucket/report.xml

  branches:
    master:
      - step:
          script:
            - npm ci
            - /opt/testcafe/docker/testcafe-docker.sh 'firefox:headless,chromium --no-sandbox --disable-dev-shm-usage' testcafe/fixtures/test-fixture.js -r xunit:reports/test-results/bitbucket/report.xml
```

With this example bitbucket provides: _2 / 1 tests failed_ while it should be: _1 / 1 tests failed_
