### ISSUE TITLE
Testcafe testcase failing on build pipeline

### ISSUE THREAD

**Issue by Yuktee2304** [DevExpress/testcafe#7058]
### What is your Scenario?

We have built some UI test cases using TestCafe node.js library. For one those test cases we are facing issues on Azure DevOps build pipeline although the test case is working fine on a local machine

### What is the Current behavior?

Key Insights:
1. The build job is going into a wait and is not terminating unless canceled.
2. Test Case execution runs fine for the same website when run on local machine.
3. TestCafe is not able to click on a 'Ok' button visible on UI but it is able to assert it's existence successfully.
4. After that the job waits indefinitely.

### What is the Expected behavior?

Test case should run on build pipeline.

### What is your public website URL? (or attach your complete example)

I cannot legally share the example source code / The application that I test displays sensitive information.

### What is your TestCafe test code?

We are using this code segment in the testcase

await t
// Choose the recipient using some logic
.click(this.toRecipientButton)
.expect(this.okButton.exists).ok()
// Working fine till this point (assertion succeeds)
.click(this.okButton);
// Not able to click on this button

This is the Selector for "OK" button
this.okButton = Selector('.classname').withAttribute('data-testid', 'searchForm_OkButton');

### Steps to Reproduce

1.Environment settings
2. Memory configuration

### TestCafe version

1.18.5

### Node.js version

v16.15.0

### Command-line arguments

npm run test

### Browser name(s) and version(s)

Chrome

### Platform(s) and version(s)

Windows 10

**Comment by Yuktee2304** [comment]
Team

Request you to please prioritize and help with the resolution.

**Comment by Aleksey28** [comment]
I could not reproduce the issue on my side:

test.js
```js
import { Selector } from 'testcafe';

fixture`Getting Started`
    .page`https://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button')

        // Use the assertion to check if the actual header text is equal to the expected one
        .expect(Selector('#article-header').innerText).eql('Thank you, John Smith!');
});
```

package.json
```json
{
  "name": "getting_started",
  "version": "1.0.0",
  "description": "",
  "main": "test.js",
  "scripts": {
    "test": "testcafe chrome:headless test.js --reporter spec,xunit:report.xml"
  },
  "repository": {
    "type": "git",
    "url": "https://alexeypopov1995@dev.azure.com/alexeypopov1995/getting_started/_git/getting_started"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "testcafe": "^1.19.0",
    "testcafe-reporter-xunit": "^2.2.1"
  }
}
```
azure-pipelines.yml
```yml
jobs:
- job: e2e_tests
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: NodeTool@0
    inputs:
      # Replace '10.14' with the latest Node.js LTS version
      versionSpec: '16.15.0'
    displayName: 'Install Node.js'
  - script: npm install
    displayName: 'Install TestCafe'
  - script: npm test
    displayName: 'Run TestCafe Tests'
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/report.xml'
      testResultsFormat: 'JUnit'
```

Please modify my project so that the problem is reproduced there and share it with me. It will be even more helpful if you create a simple working sample according to the following instructions: https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue
