### ISSUE TITLE
TestCafe 2.6.2 and later fails to start when running in GitHubActions MacOs runners for Safari Browser

### ISSUE THREAD

**Issue by eaudisio** [DevExpress/testcafe#7910]
### What is your Scenario?

TestCafe v2.6.2 and later
running on Github MacOs hosted-runner 
Safari 16.5.1 / macOS 10.15.7

Node v18

Test execution is triggered by execution the script ./test_macos.sh

-----------------------------------------------------------------
#test_macos.sh
export HOSTNAME=localhost
export PORT1=1337
export PORT2=1338

echo "--test-meta ${TEST_META}"

npx testcafe remote --test-meta $TEST_META --hostname ${HOSTNAME} --ports ${PORT1},${PORT2} &
sleep 20
open -a Safari http://${HOSTNAME}:${PORT1}/browser/connect
wait $!
-----------------------------------------------------------------

### What is the Current behavior?

After upgrading from 2.5.0 to 2.6.2 (or later) the execution fails with the following error:

--test-meta CID=C6711
Connecting 1 remote browser(s)...
Navigate to the following URL from each remote browser.
Connect URL: http://localhost:1337/browser/connect
CONNECTED Safari 16.5.1 / macOS 10.15.7
The "browsers" option from the configuration file will be ignored.
ERROR Error: EEXIST: file already exists, mkdir '/Users/runner/.testcafe-browser-tools/TestCafe Browser Tools.app/Contents/Resources'

Type "testcafe -h" for help.
Error: Process completed with exit code 1.

--------------------------------------------------

I've already confirmed that the folder "/Users/runner/.testcafe-browser-tools/" does not exist by the time testcafe is run.

### What is the Expected behavior?

Automated test cases is executed

### What is your public website URL? (or attach your complete example)

I don't have this available

### What is your TestCafe test code?

the reported issue happens even before executing any test.

### Your complete configuration file

require('dotenv').config();

module.exports = {
    "disableNativeAutomation": "true",
    "skipJsErrors": true,
    "browsers": ["chrome chrome --start-fullscreen", "firefox --start-fullscreen"],
    "src": "./test/modules/**/**.ts",
    "selectorTimeout": 45000,
    "assertionTimeout": 45000,
    "pageLoadTimeout": 180000,
    //"testExecutionTimeout": 300000,
    "color": true,
    "screenshots": {
        "takeOnFails": true,
        "pathPattern": "${DATE}_${TIME}/${BROWSER}/screenshot-${TEST}-${USERAGENT}.png"
    },
    "reporter": [
        {
            "name": "spec"
        },
        { 
            "name": 'testrail',
            "output": '' 
        }
    ],
    "hooks":{
        testRun:{
            before: async t =>{
                console.log('test started at: ' + new Date());
            },
            after: async t =>{
                console.log('test finished at: ' + new Date());
            }
        },
    }
}

### Steps to Reproduce

1. run GitHubActions workflow
  testSafariMacOs:
    if: ${{ github.event.inputs.runSafariOnMacos == 'true' }}
    name: Run TestCafe Tests on Safari & macOS
    runs-on: macos-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.5.2
      - name: Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
      - name: Install framework
        run: | 
          npm install
      - name: Run tests (macos)
        env: 
          TESTRAIL_RUN_ID: ${{ vars.TESTRAIL_RUN_ID_PETREGISTRY_SAFARI }}
          TESTRAIL_UPLOAD_SCREENSHOTS: false
        run: ./test_macos.sh
        shell: bash

3.
4.

### TestCafe version

2.6.2 (or higer)

### Node.js version

v18.16.0

### Command-line arguments

export TEST_META='CID=C6711'; export HOSTNAME=localhost; export PORT1=1337; export PORT2=1338; npx testcafe remote --test-meta $TEST_META --hostname ${HOSTNAME} --ports ${PORT1},${PORT2} & sleep 20; open -a Safari http://${HOSTNAME}:${PORT1}/browser/connect; wait $!

### Browser name(s) and version(s)

Safari 16.5.1

### Platform(s) and version(s)

macOS 10.15.7

**Comment by eaudisio** [comment]
I'm attaching all the files needed to reproduce the issue.
[macos_error_sample.zip](https://github.com/DevExpress/testcafe/files/12230552/macos_error_sample.zip)

Please let me know any additional info you might need.

Logs from GithubActions:


_Run ./test_macos.sh
  ./test_macos.sh
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    TESTRAIL_UPLOAD_SCREENSHOTS: false
--test-meta 

Connecting 1 remote browser(s)...

Navigate to the following URL from each remote browser.

Connect URL: http://localhost:1337/browser/connect

CONNECTED Safari 16.5.1 / macOS 10.15.7

ERROR Error: EEXIST: file already exists, mkdir '/Users/runner/.testcafe-browser-tools/TestCafe Browser Tools.app/Contents/Resources'

Type "testcafe -h" for help.
Error: Process completed with exit code 1._

**Comment by Aleksey28** [comment]
I got another error.
![image](https://github.com/DevExpress/testcafe/assets/32869530/9980cd5b-a740-44bf-a58e-fc10007d5b00)

Please check your example again or simply create and share a repo with a reproducible example.

Also, you can run your tests on Safari locally as we do. For this purpose, add a permission on GitHub as follows:

```yml
- name: Add permissions on MacOS
  run: |
    sudo sqlite3 "$HOME/Library/Application Support/com.apple.TCC/TCC.db" "INSERT OR REPLACE INTO access VALUES('kTCCServiceAppleEvents','com.devexpress.testcafe-browser-tools',0,2,3,1,X'fade0c0000000068000000010000000700000007000000080000001443fa4ca5141baeda21aeca1f50894673b440d4690000000800000014f8afcf6e69791b283e55bd0b03e39e422745770e0000000800000014bf4fc1aed64c871a49fc6bc9dd3878ce5d4d17c6',NULL,0,'com.apple.Safari',X'fade0c000000002c00000001000000060000000200000010636f6d2e6170706c652e53616661726900000003',NULL,1687952810);"
    sudo sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" "INSERT OR REPLACE INTO access VALUES('kTCCServiceScreenCapture','com.devexpress.testcafe-browser-tools',0,2,3,1,X'fade0c0000000068000000010000000700000007000000080000001443fa4ca5141baeda21aeca1f50894673b440d4690000000800000014f8afcf6e69791b283e55bd0b03e39e422745770e0000000800000014bf4fc1aed64c871a49fc6bc9dd3878ce5d4d17c6',NULL,0,'UNUSED',NULL,0,1687952810);"
```

**Comment by eaudisio** [comment]
I got an error when adding the step "Add permissions on MacOS" you suggested:
![Screenshot from 2023-08-07 17-28-52](https://github.com/DevExpress/testcafe/assets/84509423/6b4deacc-f43d-4de5-8ba0-b2c2bd84cac7)

**Comment by Aleksey28** [comment]
Hi @eaudisio,

There is a difference in behavior between `macos-12` (`macos-latest`) and `macos-13` GitHub images.

For the `macos-13` permission, use the step that I mentioned above:
```yml
- name: Add permissions on MacOS
  run: |
    sudo sqlite3 "$HOME/Library/Application Support/com.apple.TCC/TCC.db" "INSERT OR REPLACE INTO access VALUES('kTCCServiceAppleEvents','com.devexpress.testcafe-browser-tools',0,2,3,1,X'fade0c0000000068000000010000000700000007000000080000001443fa4ca5141baeda21aeca1f50894673b440d4690000000800000014f8afcf6e69791b283e55bd0b03e39e422745770e0000000800000014bf4fc1aed64c871a49fc6bc9dd3878ce5d4d17c6',NULL,0,'com.apple.Safari',X'fade0c000000002c00000001000000060000000200000010636f6d2e6170706c652e53616661726900000003',NULL,1687952810);"
    sudo sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" "INSERT OR REPLACE INTO access VALUES('kTCCServiceScreenCapture','com.devexpress.testcafe-browser-tools',0,2,3,1,X'fade0c0000000068000000010000000700000007000000080000001443fa4ca5141baeda21aeca1f50894673b440d4690000000800000014f8afcf6e69791b283e55bd0b03e39e422745770e0000000800000014bf4fc1aed64c871a49fc6bc9dd3878ce5d4d17c6',NULL,0,'UNUSED',NULL,0,1687952810);"
```

For `macos-12` (`macos-latest`), you need to set only one permission:
```yml
- name: Add permissions on MacOS
  run: |
    sudo sqlite3 "$HOME/Library/Application Support/com.apple.TCC/TCC.db" "INSERT OR REPLACE INTO access VALUES('kTCCServiceAppleEvents','com.devexpress.testcafe-browser-tools',0,2,3,1,X'fade0c0000000068000000010000000700000007000000080000001443fa4ca5141baeda21aeca1f50894673b440d4690000000800000014f8afcf6e69791b283e55bd0b03e39e422745770e0000000800000014bf4fc1aed64c871a49fc6bc9dd3878ce5d4d17c6',NULL,0,'com.apple.Safari',X'fade0c000000002c00000001000000060000000200000010636f6d2e6170706c652e53616661726900000003',NULL,1687952810);"
```

Another one was built into [this image](https://github.com/actions/runner-images/pull/7893).
